### PR TITLE
Trodes api integration

### PR DESCRIPTION
**Pull request by wangkf1**

### CODE REVIEW

**Comment by daliu87** [comment]
I'm getting this error when I try to run the simulator, I assume this has something to do with a change in the simulator interface with the spikegadget_python interface.  Could you elaborate more on what the change is?

`18:39:05.877 [ERROR] (MPI-01) MainThread root: ('Rank 3 tried to request channel ([5, 14]) not available in animal info.
',)
Traceback (most recent call last):
  File "/home/daliu/Src/spykshrk_realtime_wang/spykshrk/realtime/realtime_base.py", line 308, in outer
    func(self)
  File "/home/daliu/Src/spykshrk_realtime_wang/spykshrk/realtime/simulator/simulator_process.py", line 467, in main_loop
    self.mpi_recv.__next__()
  File "/home/daliu/Src/spykshrk_realtime_wang/spykshrk/realtime/simulator/simulator_process.py", line 485, in __next__
    self.process_request_message(msg)
  File "/home/daliu/Src/spykshrk_realtime_wang/spykshrk/realtime/simulator/simulator_process.py", line 493, in process_r
equest_message
    self.sim.update_cont_chan_req(self.mpi_status.source, message.channel)
  File "/home/daliu/Src/spykshrk_realtime_wang/spykshrk/realtime/simulator/simulator_process.py", line 334, in update_co
nt_chan_req
    format(dest_rank, lfp_chan))
spykshrk.realtime.simulator.simulator_process.SimulatorError: Rank 3 tried to request channel ([5, 14]) not available i$ animal info.`

**Comment by wangkf1** [comment]
I'm not sure what I changed to cause this. The exception says that a channel being requested isn't available. I could have changed the json file you used that contains the available channels. I'll look into it, though I haven't looked at this code in a while.

**Comment by wangkf1** [comment]
What script and json config are you using?

**Comment by daliu87** [comment]
The config I usually use is bond_single.json.

**Comment by wangkf1** [comment]
Added a commit that potentially fixes the bug. Let me know if it works or not.  @daliu87

**Pull request merged**
